name: tensorflow-experiments
version: '0.0.0'
category: template
synopsis: Experimental Tensorflow
description: >
    playing around with the haskell bindings of tensorflow
author: Thomas Peiselt
github: dispanser/tensorflow-experiments
license: MIT

ghc-options: -Wall
dependencies:
  - base >= 4.8.0 && <5

library:
  source-dirs: src
  dependencies:
    - tensorflow
    - tensorflow-core-ops
    - tensorflow-ops
    - tensorflow-records
    - random 
    - vector
    - HUnit


tests:
  tasty:
    source-dirs: tasty
    main: Main.hs
    dependencies:
      - tensorflow-experiments
      - hspec
      - QuickCheck
      - tasty
      - tasty-quickcheck
      - tasty-hspec

benchmarks:
  benchmark-criterion:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
    dependencies:
      - tensorflow-experiments
      - criterion
